name: CI-CD

on:
    push:
        branches:
            - main

jobs:
    test:
        name: Running unit tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 20.11.1
              uses: actions/setup-node@v4
              with:
                node-version: '20.11.1'

            - name: Install dependencies
              run: npm i

            - name: Run unit tests
              run: npm run test:unit

            - name: Generate test reports
              run: npm run test:unit:report

            - name: Upload artefatos de teste
              uses: actions/upload-artifact@v4
              with:
                name: relatorio-testes
                path: coverage/lcov-report/**

    build:
      name: Build
      runs-on: ubuntu-latest
      needs: test
      steps:
          - uses: actions/checkout@v4
          - name: Use Node.js 20.11.1
            uses: actions/setup-node@v4
            with:
              node-version: '20.11.1'

          - name: Install dependencies
            run: npm i

          - name: Run build
            run: npm run build
